// This file is auto-generated by the build script

export type TrKeys =
  /**
   * http://localhost:25560?key=common:user.name
   */
  | "common:user.name"
  /**
   * http://localhost:25560?key=common:user.email
   */
  | "common:user.email"
  /**
   * http://localhost:25560?key=common:yes
   */
  | "common:yes"
  /**
   * http://localhost:25560?key=common:name
   */
  | "common:name"
  /**
   * http://localhost:25560?key=common:qwertyuiop
   */
  | "common:qwertyuiop"
  /**
   * http://localhost:25560?key=errors:unknownError
   */
  | "errors:unknownError"
  /**
   * http://localhost:25560?key=errors:loginError
   */
  | "errors:loginError"
  /**
   * http://localhost:25560?key=errors:user.invalidPassword
   */
  | "errors:user.invalidPassword";

export const trKeys = (key: TrKeys) => key;
